version: 2.1
jobs:

  lint:
      docker:
          - image: circleci/node:stretch
      steps:
          - checkout
          - run:
              name: install linter
              command: |
                  npm install -g remark-cli remark-preset-lint-recommended
          - run:
              name: lint the markdown files
              # for defining .remarkrc, see https://github.com/remarkjs/remark-lint#configuring-remark-lint
              command: |
                  remark --version
                  remark _pages _posts --frail
    build:
        docker:
            - image: circleci/ruby:stretch
        steps:
            - checkout

            # Restore gem cache to speed up installations
            - restore_cache:
                keys:
                  - gem-cache-0-{{ checksum "./Gemfile" }}

            - run:
                name: install
                command: |
                    gem install jekyll bundler
                    bundle install --path vendor/bundle
            - run:
                name: build
                command: |
                    bundle exec jekyll build --baseurl /0/_site
            - store_artifacts:
                path: _site
                destination: _site

            # Store gem cache
            - save_cache:
                key: gem-cache-0-{{ checksum "./Gemfile" }}
                paths:
                  - vendor/bundle

workflows:
    lint_and_build:
        jobs:
            - lint
            - build
