# Javascript Node CircleCI 2.0 configuration file
#
# Check {{ '/2.0/language-javascript/' | docs_url }} for more details
#
# deploy reference: https://circleci.com/blog/publishing-npm-packages-using-circleci-2-0/
#
version: 2
jobs:
  node-latest: &test
    docker:
      - image: node:latest
    working_directory: ~/cli
    steps:
      - checkout
      - restore_cache: &restore_cache
          keys:
            - v1-npm-{{checksum ".circleci/config.yml"}}-{{checksum "yarn.lock"}}
            - v1-npm-{{checksum ".circleci/config.yml"}}
            - v1-npm-
      - run:
          name: Install dependencies
          command: yarn
      - run: ./bin/run --version
      - run: ./bin/run --help
      - run:
          name: Testing
          command: yarn test
      - persist_to_workspace:
          root: ~/cli
          paths: .
  node-14:
    <<: *test
    docker:
      - image: node:14
  node-12:
    <<: *test
    docker:
      - image: node:12
  cache:
    <<: *test
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn
      - save_cache:
          key: v1-npm-{{checksum ".circleci/config.yml"}}-{{checksum "yarn.lock"}}
          paths:
            - ~/cli/node_modules
            - /usr/local/share/.cache/yarn
            - /usr/local/share/.config/yarn
  deploy:
    <<: *test
    steps:
      - attach_workspace:
          at: ~/cli
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/cli/.npmrc
      - run:
          name: Publish package
          command: npm publish
workflows:
  version: 2
  'ytdl':
    jobs:
      - node-latest
      - node-14
      - node-12
      - cache:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - deploy:
          requires:
            - cache
            - node-latest
            - node-14
            - node-12
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/

